[package]
name = "cucumber-rust-repro"
version = "0.1.0"
authors = ["Bryce Fisher-Fleig <brycefisher@users.noreply.github.com>"]
edition = "2018"

[[test]]
name = "cucumber"
harness = false

[dev-dependencies]
cucumber = { package = "cucumber_rust", version = "^0.6.0" } 
